CC = g++

OBJS = bat.h bat.cpp bear.h bear.cpp bird.h bird.cpp boss.h boss.cpp deer.h deer.cpp enemy.h enemy.cpp hero.h hero.cpp rat.h rat.cpp wolf.h wolf.cpp main.cpp

COMPILER_FLAGS = -std=c++11

OBJ_NAME = adventure_battle


all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) -o $(OBJ_NAME)